import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import sim_img from "../public/img/simul_photo.png";
import skills_pl from "../public/img/skills_pl.png";
import skills_wd from "../public/img/skills_wd.png";
import skills_db from "../public/img/skills_db.png";
import skills_bd from "../public/img/skills_bd.png";
import skills_o from "../public/img/skills_o.png";
import project1 from "../public/img/proj1.png"
import project2 from "../public/img/proj1.png"
import project3 from "../public/img/proj1.png"
import project4 from "../public/img/proj1.png"
import project5 from "../public/img/proj1.png"
import project6 from "../public/img/proj1.png"
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>Simul's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-800">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons max-sm:text-sm dark:text-white">
              Developed By: Simul
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-orange-400 to-red-400 text-white px-4 py-2 rounded-lg ml-8"
                  href="https://www.linkedin.com/in/simul-bista/"
                  target="_blank"
                >
                  LinkedIn
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center py-10 px-5">
            <h2 className="text-5xl py-2 text-orange-400 font-medium  max-sm:text-4xl">
              Simul Bista
            </h2>
            <div className="text-3xl flex justify-center gap-5 pt-3 dark:text-green-400">
              <a href="https://www.linkedin.com/in/simul-bista/" target="_blank"><AiFillLinkedin /></a>
              <a href="https://github.com/simulbista" target="_blank"><AiFillGithub /></a>
            </div>
            <h3 className="text-sm py-2 leading-10 font-semibold text-green-600 dark:text-orange-400">
              Software Developer
            </h3>
            <p className="text-justify text-base dark:text-white">
              With my extensive background in Java and over three years of
              experience as a software developer, I bring valuable project
              management skills to the table. I have a proven track record of
              successfully managing multiple projects from start to finish,
              always striving to create impactful and innovative solutions. As a
              dedicated and proactive team player, I take full responsibility
              for the projects I am a part of and am always searching for ways
              to have a positive impact on the wider community.
            </p>
          </div>

          <div className="relative mx-auto bg-gradient-to-b from-orange-400 to-red-400 text-white rounded-full w-60 h-80 shadow-2xl mt-10 overflow-hidden">
            <Image src={sim_img} fill="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div className="text-center pt-10 font-semibold">
            <h3 className="text-5xl pt-20 pb-10 text-orange-400 font-medium">
              Skills
            </h3>
          </div>
          <div className="flex justify-evenly flex-wrap gap-5">
            <div className="scale-90 shadow-lg p-10 rounded-xl transition ease-in-out hover:scale-100 hover:shadow-orange-400 duration-500 max-sm:w-full h-fit lg:h-[520px] dark:bg-white">
              <Image
                className="mx-auto w-16 mb-5 red "
                src={skills_pl}
                width={100}
                height={100}
              />
              <h3 className="text-sm leading-10 font-semibold text-green-600">
                Programming Languages
              </h3>
              <div>
                <ul className="list-disc pl-5">
                  <li>Java</li>
                  <li>C#</li>
                  <li>JavaScript</li>
                </ul>
              </div>
            </div>
            <div className="scale-90 shadow-lg p-10 rounded-xl transition ease-in-out hover:scale-100 hover:shadow-orange-400 duration-500 max-sm:w-full h-fit lg:h-[520px] dark:bg-white">
              <Image
                className="mx-auto w-16 mb-5"
                src={skills_wd}
                width={100}
                height={100}
              />
              <h3 className="text-sm leading-10 font-semibold text-green-600">
                Web Development Technologies
              </h3>
              <div>
                <ul className="list-disc pl-5">
                  <li>JSPs</li>
                  <li>Java Servlets</li>
                  <li>JDBC</li>
                  <li>Node.js</li>
                  <li>Express.js</li>
                  <li>HTML</li>
                  <li>CSS</li>
                  <li>Tailwind CSS</li>
                  <li>XML</li>
                  <li>JSON</li>
                  <li>Web APIs</li> 
                  <li>WordPress</li>
                </ul>
              </div>
            </div>
            <div className="scale-90 shadow-lg p-10 rounded-xl transition ease-in-out hover:scale-100 hover:shadow-orange-400 duration-500 max-sm:w-full h-fit lg:h-[520px] dark:bg-white">
              <Image
                className="mx-auto w-16 mb-5"
                src={skills_db}
                width={100}
                height={100}
              />
              <h3 className="text-sm leading-10 font-semibold text-green-600">Databases</h3>
              <div>
                <ul className="list-disc pl-5">
                  <li>Oracle (PL/SQL)</li>
                  <li>MySQL</li>
                </ul>
              </div>
            </div>
            <div className="scale-90 shadow-lg p-10 rounded-xl transition ease-in-out hover:scale-100 hover:shadow-orange-400 duration-500 max-sm:w-full h-fit lg:h-[520px] dark:bg-white">
              <Image
                className="mx-auto w-16 mb-5"
                src={skills_bd}
                width={100}
                height={100}
              />
              <h3 className="text-sm leading-10 font-semibold text-green-600">
                Big Data Technologies
              </h3>
              <div>
                <ul className="list-disc pl-5">
                  <li>Hadoop</li>
                  <li>HDFS</li>
                  <li>Hive</li>
                </ul>
              </div>
            </div>
            <div className="scale-90 shadow-lg p-10 rounded-xl transition ease-in-out hover:scale-100 hover:shadow-orange-400 duration-500 max-sm:w-full h-fit lg:h-[520px] dark:bg-white">
              <Image
                className="mx-auto w-16 mb-5"
                src={skills_o}
                width={100}
                height={100}
              />
              <h3 className="text-sm leading-10 font-semibold text-green-600">Others</h3>
              <div>
                <ul className="list-disc pl-5">
                  <li>Git</li>
                  <li>Linux</li>
                  <li>Bash Scripting</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section>
        <div className="text-center pt-10 font-semibold">
            <h3 className="text-5xl pt-20 pb-10 text-orange-400 font-medium">
              Projects
            </h3>
        </div>
          <div className="flex flex-col gap-10 py-10 md:flex-row md:flex-wrap">
            <div className="basis-1/3 flex-1 lg:basis-1/4 bg-slate-500 p-5 rounded-lg  dark:bg-white scale-90 hover:scale-100 ease-in-out delay-150 duration-300">
              <Image className="rounded-lg object-cover width={`100%`} height={`100%`}" src={project1}/>
              <div>
                <ul className="flex gap-5 py-5 items-center">
                  <li>Proj Title</li>
                  <li><a href="https://github.com/simulbista" target="_blank"><AiFillGithub /></a></li>
                </ul>
                <p>This project is about blabla and blablaThis project is about blabla and blablaThis project is about blabla and blabla</p>
              </div>
            </div>
            <div className="basis-1/3 flex-1 lg:basis-1/4 bg-slate-500 p-5 rounded-lg  dark:bg-white scale-90 hover:scale-100 ease-in-out delay-150 duration-300">
              <Image className="rounded-lg object-cover width={`100%`} height={`100%`}" src={project1}/>
              <div>
                <ul className="flex gap-5 py-5 items-center">
                  <li>Proj Title</li>
                  <li><a href="https://github.com/simulbista" target="_blank"><AiFillGithub /></a></li>
                </ul>
                <p>This project is about blabla and blablaThis project is about blabla and blablaThis project is about blabla and blabla</p>
              </div>
            </div>
            <div className="basis-1/3 flex-1 lg:basis-1/4 bg-slate-500 p-5 rounded-lg  dark:bg-white scale-90 hover:scale-100 ease-in-out delay-150 duration-300">
              <Image className="rounded-lg object-cover width={`100%`} height={`100%`}" src={project1}/>
              <div>
                <ul className="flex gap-5 py-5 items-center">
                  <li>Proj Title</li>
                  <li><a href="https://github.com/simulbista" target="_blank"><AiFillGithub /></a></li>
                </ul>
                <p>This project is about blabla and blablaThis project is about blabla and blablaThis project is about blabla and blabla</p>
              </div>
            </div>     
            <div className="basis-1/3 flex-1 lg:basis-1/4 bg-slate-500 p-5 rounded-lg  dark:bg-white scale-90 hover:scale-100 ease-in-out delay-150 duration-300">
              <Image className="rounded-lg object-cover width={`100%`} height={`100%`}" src={project1}/>
              <div>
                <ul className="flex gap-5 py-5 items-center">
                  <li>Proj Title</li>
                  <li><a href="https://github.com/simulbista" target="_blank"><AiFillGithub /></a></li>
                </ul>
                <p>This project is about blabla and blablaThis project is about blabla and blablaThis project is about blabla and blabla</p>
              </div>
            </div>
            <div className="basis-1/3 flex-1 lg:basis-1/4 bg-slate-500 p-5 rounded-lg  dark:bg-white scale-90 hover:scale-100 ease-in-out delay-150 duration-300">
              <Image className="rounded-lg object-cover width={`100%`} height={`100%`}" src={project1}/>
              <div>
                <ul className="flex gap-5 py-5 items-center">
                  <li>Proj Title</li>
                  <li><a href="https://github.com/simulbista" target="_blank"><AiFillGithub /></a></li>
                </ul>
                <p>This project is about blabla and blablaThis project is about blabla and blablaThis project is about blabla and blabla</p>
              </div>
            </div>
            <div className="basis-1/3 flex-1 lg:basis-1/4 bg-slate-500 p-5 rounded-lg  dark:bg-white scale-90 hover:scale-100 ease-in-out delay-150 duration-300">
              <Image className="rounded-lg object-cover width={`100%`} height={`100%`}" src={project1}/>
              <div>
                <ul className="flex gap-5 py-5 items-center">
                  <li>Proj Title</li>
                  <li><a href="https://github.com/simulbista" target="_blank"><AiFillGithub /></a></li>
                </ul>
                <p>This project is about blabla and blablaThis project is about blabla and blablaThis project is about blabla and blabla</p>
              </div>
            </div>       
          </div>
        </section>
      </main>
    </div>
  );
}
